version: "3"
services:
    database:
        image: postgres:latest
        container_name: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: scott
            POSTGRES_PASSWORD: tiger
            POSTGRES_DB: latelier

    backend:
        build: .
        restart: on-failure
        ports:
            - 8080:8080
        depends_on:
            - database
        links:
            - database